### WEKA 2c dataset with decision tree

In [35]:
import pandas as pd
data_origin = pd.read_csv("../datasets/column_2C_weka.csv")

In [36]:
data_origin.head()
# data_origin.info()

pelvic_incidence  pelvic_tilt numeric  lumbar_lordosis_angle  sacral_slope  \
0         63.027817            22.552586              39.609117     40.475232   
1         39.056951            10.060991              25.015378     28.995960   
2         68.832021            22.218482              50.092194     46.613539   
3         69.297008            24.652878              44.311238     44.644130   
4         49.712859             9.652075              28.317406     40.060784   

   pelvic_radius  degree_spondylolisthesis     class  
0      98.672917                 -0.254400  Abnormal  
1     114.405425                  4.564259  Abnormal  
2     105.985135                 -3.530317  Abnormal  
3     101.868495                 11.211523  Abnormal  
4     108.168725                  7.918501  Abnormal

In [37]:
label_categorical = data_origin.get('class')
features = data_origin.drop('class', axis=1)

# label_categorical.head()
# features.head()

In [38]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

#Preprocessing the features
#scaling the features
standardScaler = StandardScaler()
features_norm = standardScaler.fit_transform(features)
print(features_norm)


#instanciating the label encoder
label_encoder = LabelEncoder()
#transform label column
label_array = label_encoder.fit_transform(label_categorical)
label = pd.DataFrame(label_array, columns=['class'])
# print(label_array)
# label.head()
# label.info
# counts = label.value_counts()
# print(counts)

[[ 0.14708636  0.50136873 -0.6651769  -0.18495031 -1.4476468  -0.70805942]
 [-1.24586434 -0.74876898 -1.45300075 -1.0415207  -0.26438488 -0.57955637]
 [ 0.4843695   0.46793218 -0.09926175  0.2730833  -0.89768556 -0.79542095]
 ...
 [ 0.05520137  0.51561812 -0.31097748 -0.31356364  0.58289256 -0.77348834]
 [-0.88582307 -0.88565951 -0.55861259 -0.47712775  0.04702109 -0.69554822]
 [-1.54892681 -1.24785954 -0.82539423 -1.05855695  0.45311695 -0.70658867]]


In [39]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

#Setting the values for GridSearch
kfold = KFold(n_splits=5)
min_split = list(np.arange(2,10,1))
max_split = list(np.arange(3,12,1))
algorithms = ['gini','entropy', 'log_loss']
grid_values = {'min_samples_split':min_split, 'max_depth':max_split, 'criterion':algorithms}

#New model
model = DecisionTreeClassifier()

#Grid creation
gridDecisionTree = GridSearchCV(estimator=model, param_grid=grid_values, cv=kfold)
gridDecisionTree.fit(features_norm, label)

#printing results
print(f'Min_split: {gridDecisionTree.best_estimator_.min_samples_split}')
print(f'Max_split: {gridDecisionTree.best_estimator_.max_depth}')
print(f'Chosen algorithm: {gridDecisionTree.best_estimator_.criterion}')
print(f'R2 Coefficient: {gridDecisionTree.best_score_:.3f}')

Min_split: 3
Max_split: 11
Chosen algorithm: log_loss
R2 Coefficient: 0.674
